### ISSUE TITLE
Still fetch withdrawed reblog notification, but don't fetch withdrawed like notification items.

### ISSUE THREAD

**Issue by HawtinZeng** [neet/masto.js#1028]
Replication: accountA reblog one status of accountB, accountB can get a notification related to the reblog, but after accountA withdrawing the reblog, accountB still can see a notification related to the reblog. the withdraw of like is perfect to withdraw the like notification, Related api: .v1.notifications.list(options), version: masto@5.11.3

**Comment by neet** [comment]
I believe this is due to the cache layer of your Mastodon instance since we don't have any logic that persists response data.
Feel free to reopen this issue if you think you still have a problem.
