### ISSUE TITLE
Support Mastodon filter v1 API

### ISSUE THREAD

**Issue by KyoSakuyo** [neet/masto.js#1059]
Gotosocial only supports Mastodon filter v1 API. 

It seems like neither Elk nor Phanpy could handle filter requests from gotosocial.

https://github.com/superseriousbusiness/gotosocial/pull/2594

**Comment by neet** [comment]
Hi @KyoSakuyo, thank you for reporting an issue. I believe we already have a backward compatibility for all the v1 APIs including the filters. I suppose it's just Elk and Phanpy not supporting it.

Here are some usage
https://github.com/neet/masto.js/blob/e4f0eb75e7d6ccb3d46e574ff0492c74a10fae77/tests/rest/v1/filters.spec.ts#L1-L12
