### ISSUE TITLE
`TypeError: AbortSignal.timeout is not a function` occurs in Expo

### ISSUE THREAD

**Issue by dccarmo** [neet/masto.js#1097]
Hi,

We're developing an Expo app, and Masto works great for the web version. But when running on either iOS or Android, it seems to not work. I was able to create a reproducible repository here: https://github.com/dccarmo/MastodonInstance

You just have to run `npm i` and then `npm run ios` or `npm run android` to see the issue. You might need to do Expo initial setup to run on simulators: https://docs.expo.dev/workflow/ios-simulator/ or https://docs.expo.dev/workflow/android-studio-emulator/.

This is the error we're seeing: `TypeError: AbortSignal.timeout is not a function (it is undefined)`. It happens when you try to fetch an endpoint (such as `verifyCredentials`).

On a side note, unrelated to the reproducible issue, when trying to print the client that gets returned when you call `createRestAPIClient`, React Native hermes engine fails with this error: `TypeError: Cannot determine default value of object`. I found a similar issue here: https://github.com/facebook/hermes/issues/205.

**Comment by neet** [comment]
HI @dccarmo, thank you for reporting an issue.

> TypeError: AbortSignal.timeout is not a function

This makes sense because Masto.js internally use `AbortSignal.timeout` to manage timeout seconds and was newly added in v18+ even in Node.js. I'm aware that Expo has this type of compatibility issue and some of then can be resolved by using polyfill as a workaround as in #890.

> TypeError: Cannot determine default value of object

I guess this can be a similar issue as #1029, but have no idea how this can happen only in Expo.

I'll set up React Native env locally and try look into these problems when I have time. I'll keep you informed.

**Comment by dccarmo** [comment]
Hi @neet, thank you for your reply.

I tried using this polyfill for AbortController: https://www.npmjs.com/package/abortcontroller-polyfill

But unfortunately it didn't work. 

Thank you for you help into turning masto.js such a great library.

**Comment by neet** [comment]
In #1099 I changed the default behaviour for `createRestAPIClient` to use default timeout duration of Fetch API which means if you don't set anything for configuration, you will automatically opt-out of timeout handling (and so AbortSignal.timeout).

Although I haven't tested if this actually be a solution for this issue in Expo, [I tested it works in an environment that lacks `AbortSignal.timeout`](https://github.com/neet/masto.js/blob/bbfb99d08772388be6dfddf89c1d78f876e28417/src/adapters/config/http-config.spec.ts#L94) so it would improve the situation.

@dccarmo Can you check whether if the error solved? If you get another problem, I'm willing to look into it as well.

**Comment by dccarmo** [comment]
@neet the latest version (6.7.5) fixed the issue on React Native! It's all working great, thank you so much!
