### ISSUE TITLE
Incomplete mastodon 3.0 support : use removed dissmiss notification endpoint

### ISSUE THREAD

**Issue by wryk** [neet/masto.js#169]
`POST /api/v1/notifications/dismiss?id=:id` is deprecated since 2.6 and removed since 3.0 (see https://github.com/tootsuite/mastodon/pull/11214)

I didn't make a PR because I don't know if you want your lib to be compatible with mastodon before 2.6.

**Comment by neet** [comment]
Thank you for your report. My stance for backward compatibility with Mastodon is to recommend using an older version of Masto.js.

So yes, This is a lack of support for 3.0 🙇

**Comment by neet** [comment]
The fix was released as `masto@2.8.1` 👍
