### ISSUE TITLE
Support Deno

### ISSUE THREAD

**Issue by neet** [neet/masto.js#249]
~~working at: https://github.com/neet/deno-masto~~

**Update:** I used to be planning a new library dedicated to Deno, but since Deno supported a compatibility layer to Node.js, I will keep offering Node.js one for a while. Please report a bug if our library doesn't work using Node.js-compat mode.

**Comment by eai04191** [comment]
https://dash.deno.com/playground/small-kingfisher-54
For now, it seems to work to some extent with the power of esm.sh. (So yes, you can host your bot for free with deno deploy)
However, I have not yet tested whether the error does not occur in all cases.

**Comment by neet** [comment]
@eai04191 Thank you for the research. That's interesting.
This issue has been created almost three years ago, and I'm not caught up on the latest Deno, but I'm aware that Deno has introduced the Node.js compatibility layer. Therefore I suppose Masto.js now work on Deno to some extent as you said.

However, since I didn't test our library on Deno very well at this point, I suppose there could be some error. Just let me know by comments or issues if you have any trouble with Deno
