### ISSUE TITLE
Repeated "MastoUnprocessableEntityError" on upgrade from masto.js 2.x to 3.x

### ISSUE THREAD

**Issue by lostfictions** [neet/masto.js#303]
Hi, I upgraded from `masto@2.5.4` to `masto@3.5.1` and renamed the `uploadMediaAttachment` method and response object parameters as indicated by the [breaking changes in the release notes for 3.0.0](https://github.com/neet/masto.js/releases/tag/v3.0.0), but now I'm getting a `MastoUnprocessableEntityError` whenever I try to make a post with uploaded media. Previously it used to work fine.

The full error:

> MastoUnprocessableEntityError: Cannot attach files that have not finished processing. Try again in a moment!

The code I was using with `masto@2.5.4`, which worked fine:

```ts
// ...

const { id } = await masto.uploadMediaAttachment({
  file: createReadStream(filename),
  description: title
});

const { created_at, uri } = await masto.createStatus({
  status: title,
  visibility: "public",
  media_ids: [id]
});
```

The code I am using with `masto@3.5.1`, which throws the exception:

```ts
// ...

const { id } = await masto.createMediaAttachment({
  file: createReadStream(filename),
  description: title,
});

const { createdAt, uri } = await masto.createStatus({
  status: title,
  visibility: "public",
  mediaIds: [id],
});
```

Is it possible this is a change in the Mastodon API behaviour [introduced in 3.1.0](https://github.com/neet/masto.js/releases/tag/v3.1.0) when using the `v2/media` endpoint? If so, that seems like a breaking change.

**Comment by lostfictions** [comment]
From the discussion here https://github.com/tootsuite/mastodon/pull/13210 it's not clear how API clients should know when the attachment has finished processing when using the `v2/media` endpoint.

**Comment by neet** [comment]
I appreciate your research. In #304  I've just added new methods `Masto#fetchMediaAttachment` which does the exact same thing as `GET /api/v1/media/:id` and `Masto#waitForMediaAttachment` which handles polling stuff. You can refer to the latest example on this repository for usage.

I think it'd be better if Masto could handle the polling stuff in the `Masto#createMediaAttachment`, though I also want to keep it simple that does not do any magic on the background. Let me keep them separated at this moment because I cannot assert that there are no people who want to use the data of media in progress.

**Comment by neet** [comment]
The fix for this has been released as `3.6.0`. I'm planning to provide two ways for creating new media attachment (one is with polling and the other is the original legacy version) on the next major release so I keep this issue opened. Any opinions are welcome 🙏

**Comment by lostfictions** [comment]
Thank you very much for the quick response and solution! That sounds great to me. The only thing I'm wondering is if `Masto#waitForMediaAttachment` should perhaps have a timeout or maximum number of retries by default? If not I might do something like this in practice, just to ensure that a slow or malicious server doesn't hang my program indefinitely:

```ts
const { id } = await masto.createMediaAttachment({
  file: createReadStream(filename),
  description: title,
});

await Promise.race([
  waitForMediaAttachment(id),
  new Promise((_, rej) => setTimeout(() => rej('Maximum timeout exceeded!', 1000 * 30)
])

await masto.createStatus({
  status: title,
  visibility: "public",
  mediaIds: [id],
});
```

**Comment by lostfictions** [comment]
Great! Thanks for your work on this!

**Comment by neet** [comment]
As of masto@4.0.0, the polling is enabled by default. To skip waiting for the media process and access the incomplete data, you can use new `skipPolling` param available in both `attachments.create` and `attachments.update`.
https://neet.github.io/masto.js/interfaces/repositories_media_attachment_repository.createmediaattachmentparams.html#skippolling
