### ISSUE TITLE
`excludeReplies` from function `getStatusesIterable` not working?

### ISSUE THREAD

**Issue by dzx-dzx** [neet/masto.js#392]
Setting it to true doesn't seem to take any effect. The test code is:
```
const statuses = await masto.accounts.getStatusesIterable("33", { excludeReplies: false }).next()
console.log(statuses)
```
Some statuses do have `inReplyToId` property that is not `null`.
In [the doc](https://docs.joinmastodon.org/methods/accounts/#retrieve-information), only `id` can be provided, though it mentioned `exclude_reblogs`.

**Comment by neet** [comment]
@dzx-dzx According to the implementation of tootsuite/mastodon, `exclude_replies` doesn't always mean that no replies are included in the response.

https://github.com/tootsuite/mastodon/blob/e78d06eecfb21de6aedf39fd7c63d9aa68f7033c/app/models/status.rb#L89

I assume `inReplyToId` you got is your own status, and that is proper behavior. If you really want to exclude all replies from it, you can just

```ts
const statuses = await masto
  .accounts.getStatusesIterable("33", { excludeReplies: false })
  .next()
  .then(response => response.filter((status) => status.inReplyToId == null)));
```

If you think we still have an issue, feel free to reopen it.
