### ISSUE TITLE
Mistyping `in_reply_to_id` as `inReplyToId`?

### ISSUE THREAD

**Issue by dzx-dzx** [neet/masto.js#394]
https://github.com/neet/masto.js/blob/b32498294d30e6329881a32eb5e2f978878e0202/src/repositories/status-repository.ts#L108
Should be in correspond to https://docs.joinmastodon.org/methods/statuses/#parent-and-child-statuses
I failed to find any code that processed the result, and so I suspect `inReplyToId` will always be `undefined`.

**Comment by neet** [comment]
I could not get any `undefined` as long as it is a reply that belongs to another status. Could you please provide a reproduction repository of this issue?

FYI, Masto converts JSON payloads `camelCase` into `snake_case` before sending the payload to the server in the `SerializerImpl` class, and likewise, it also converts `snake_case` into `camelCase` after receiving the response.
https://github.com/neet/masto.js/blob/d2695a049e8ff30695d93166566f0ce8b4d67d7d/src/serializers/serializer-impl.ts#L37

**Comment by dzx-dzx** [comment]
![图片](https://user-images.githubusercontent.com/31068367/115953470-521a7680-a51e-11eb-9c5e-4ad9f8d31cd7.png)
![图片](https://user-images.githubusercontent.com/31068367/115953517-855d0580-a51e-11eb-9262-4688c63df1cf.png)

**Comment by neet** [comment]
I confirmed that arrays inside an object will not be converted into camelCase and vice versa. I've just created a patch #394 and it's going to be released soon

**Comment by dzx-dzx** [comment]
> 
> 
> I confirmed that arrays inside an object will not be converted into camelCase and vice versa. I've just created a patch #394 and it's going to be released soon

Thanks a lot!
