### ISSUE TITLE
Detecting stream disconnection?

### ISSUE THREAD

**Issue by mitchellurgero** [neet/masto.js#616]
I don't see an event type that would help with stream detection, has anyone been able to figure out how to do this?

**Comment by neet** [comment]
I'm intentionally not making some of the WS features public to hide implementations, but the `close` event sounds good to be accessible.

For now, I think you can use this workaround to directly access an internal WebSocket instance and subscribe to `close` event

```ts
const stream = await masto.stream.streamPublicTimeline();

(stream as any).ws.on('close', () => {
  console.log('Disconnected!');
});
```
