### ISSUE TITLE
Add support for new v4 admin API endpoints

### ISSUE THREAD

**Issue by selfagency** [neet/masto.js#678]
Though they're not yet officially documented, the following new endpoints will exist in Mastodon v4 which is being released tomorrow.

- [managing domain allows](https://github.com/mastodon/mastodon/pull/18668)
- [managing domain blocks](https://github.com/mastodon/mastodon/pull/18247)
- [managing e-mail domain blocks](https://github.com/mastodon/mastodon/pull/19066)
- [managing canonical e-mail blocks](https://github.com/mastodon/mastodon/pull/19067)
- [managing IP blocks](https://github.com/mastodon/mastodon/pull/19065)

**Comment by JacksonSamuel42** [comment]
I will work in this implementation @neet

**Comment by neet** [comment]
@JacksonSamuel42 Thanks! I'm willing to review it 👍

**Comment by JacksonSamuel42** [comment]
@neet  I'm done implementing the admin-domain-blocks route but I'm having trouble testing this as I don't have any admin privileges on mastodon any ideas how I can test this?

**Comment by neet** [comment]
@JacksonSamuel42 Ideally I want you to verify that it works on the actual Mastodon instance, but if you could confirm that it sends a proper HTTP request I can merge it.

**Comment by JacksonSamuel42** [comment]
@neet ok i will push

**Comment by neet** [comment]
Kudos @JacksonSamuel42 for #741 #744 #746  #752 #759 🎉
