### ISSUE TITLE
Cannot parse JSON response with Axios 1.2.0

### ISSUE THREAD

**Issue by MikeHuntington** [neet/masto.js#695]
Using the code example on this repos readme, The login method throws an error (using Mastodon v4.0.2)

```
const masto = await login({
    url: "https://my-domain.app",
    accessToken: "_access_token",
  });
```

```
TypeError: Cannot read properties of undefined (reading 'urls')
    at file:///node_modules/masto/dist/index.mjs:3358:48
    at step (file:///node_modules/masto/dist/index.mjs:101:23)
    at Object.next (file:///node_modules/masto/dist/index.mjs:82:53)
    at fulfilled (file:///node_modules/masto/dist/index.mjs:72:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bertez** [comment]
I'm getting the same error

**Comment by bertez** [comment]
ok, I found the error... it's the axios dependency... it works with axios 1.1.3 but not with axios 1.2.0

a quick temporary fix is forcing that axios version as dependency in the package.json:

```json
"dependencies": {
    ...
    "axios": "1.1.3"
    ...
},
```

**Comment by neet** [comment]
Thanks @bertez for pointing out the cause. A bug in Axios 1.2.0 seemed to cause the issue. I temporarily fixed the Masto dependency so npm will install the exact same version as 1.1.3.

As soon as https://github.com/axios/axios/issues/5296 is fixed I will upgrade Axios to the latest version.
