### ISSUE TITLE
Add Account->Tags API

### ISSUE THREAD

**Issue by Shinigami92** [neet/masto.js#708]
https://docs.joinmastodon.org/methods/tags

get: https://docs.joinmastodon.org/methods/tags/#get
follow: https://docs.joinmastodon.org/methods/tags/#follow
unfollow: https://docs.joinmastodon.org/methods/tags/#unfollow

followed_tags: https://docs.joinmastodon.org/methods/followed_tags/#get

And maybe we need to to update the types for https://docs.joinmastodon.org/entities/Tag

**Comment by neet** [comment]
Pre released as [4.7.0-rc1](https://www.npmjs.com/package/masto/v/4.7.0-rc1)
