### ISSUE TITLE
Support for GoToSocial

### ISSUE THREAD

**Issue by matthewp** [neet/masto.js#713]
GoToSocial is an alternative server that uses the same API as Mastodon. Many Mastodon clients, such as Pinafore, work with GoToSocial.

masto.js currently does not, mostly because of the version checks. I think this is probably easily fixed with some changes to the version decorator.

I'd be happy to contribute some fixes if you would accept them. thanks!

**Comment by neet** [comment]
@matthewp Is the` disableVersionCheck` option resolve your problem? You may want to see #666

**Comment by matthewp** [comment]
That could be helpful! I'll test this in the client I'm working on (Elk). I believe there is one other place that does semver checking outside of the version decorator. If I find that one I can send a PR to use this config.

**Comment by neet** [comment]
It would be the lines below. This is for backward compatibility so we probably need another option to forcibly use `Sec-Websocket-Protocol`.

https://github.com/neet/masto.js/blob/291805e51a54de91270a037b39307a873c5bbc05/src/ws/base-ws.ts#L20-L26

> I can send a PR to use this config.

Thank you so much! I'm willing to review it 👍

**Comment by matthewp** [comment]
Yes, I think that's the one. This throws for GoToSocial at the moment because its version is not a valid semver. So we'd need to use `disableVersionCheck` here too, or make masto.js fully support GoToSocial.
