### ISSUE TITLE
Deleted status IDs (large numbers) are wrong for streaming

### ISSUE THREAD

**Issue by cheeaun** [neet/masto.js#750]
I'm using streaming with such code:

```js
const stream = await masto.stream.streamUser();
…
stream.on('delete', (statusID) => {
  console.log('DELETE', statusID);
  // Do something with deleted status
});
```

I realised the ID was wrong when I check it in the console log.

<img width="399" alt="Screenshot 2022-12-12 at 11 54 52 AM" src="https://user-images.githubusercontent.com/2296/206958176-2d2add67-8a3a-41e6-9c4c-c24b82420c2e.png">

I checked in the Websocket logs, the ID is different.

<img width="772" alt="Screenshot 2022-12-12 at 11 54 23 AM" src="https://user-images.githubusercontent.com/2296/206958200-d90b97a3-9296-406d-8644-16e02e346920.png">

I debugged and found a potential bug with this line in `src/serializers/serializer-native-impl.ts`: https://github.com/neet/masto.js/blob/6f9e940f72e92aaa870dc11de06d4be6cc39238c/src/serializers/serializer-native-impl.ts#L41

I try `JSON.parse` it in console log:

<img width="356" alt="Screenshot 2022-12-12 at 11 53 38 AM" src="https://user-images.githubusercontent.com/2296/206958623-d375ffd9-0e5b-4e83-bbd6-d52c6bb005a2.png">

So this seems like a known issue with `JSON.parse` with large numbers 😭 

Note: I'm using masto.js v4.9.1

**Comment by JacksonSamuel42** [comment]
this is the JSON problem with large numbers  

it can be resolved with lossless-json or json-bigint
`
  import {parse} from "lossless-json"
  return transformKeys(parse(data), camelCase); 
`

**Comment by neet** [comment]
@JacksonSamuel42 You're right, but ID should be parsed as a string in the first place, as well as `Status.id`.
