### ISSUE TITLE
Typescript: Client type is not exported

### ISSUE THREAD

**Issue by HappyCerberus** [neet/masto.js#776]
I'm trying to use this library with VUE.

The problematic part is that the Client type is not exported. So if I want to share a logged-in client across components, I either need to use `any` or keep re-creating it from scratch all the time.

My original idea was to create the client in a "login" component, which will also verify the credentials and then pass it around.

EDIT: as a workaround, I'm doing this `type Client = Awaited<ReturnType<typeof login>>;`

**Comment by neet** [comment]
To keep data types related to Mastodon segregated, and making other modules that are specific to this library not affect to them, we are exporting all entities and resource types under the namespace `mastodon`. 

```ts
import { mastodon } from “masto”;

let client: mastodon.Client = await login(…)
```

**Comment by likidu** [comment]
@neet, thanks for the tip. I felt it might be helpful to have this information in the doc or README so others are using Typescript can find this update easily. As I encountered the same problem and found this.

**Comment by MattiJarvinen** [comment]
Just stumbled on this today... Maybe documentation could state this more clearly.

**Comment by neet** [comment]
Thank you for your valuable opinions. I will consider it in future updates 👍
