### ISSUE TITLE
error when trying to upload a media attachment with masto@5.4.0

### ISSUE THREAD

**Issue by lostfictions** [neet/masto.js#813]
Hi there, this code works for me in `masto@4.2.4`:

```ts
import { login } from "masto";
import { createReadStream } from "fs";

void (async () => {
  const client = await login({
    url: process.env["MASTODON_SERVER"],
    accessToken: process.env["MASTODON_TOKEN"],
    timeout: 30_000,
  });

  const { id } = await client.mediaAttachments.create({
    file: createReadStream("test.png"),
  });

  const res = await client.statuses.create({
    status: "test",
    visibility: "unlisted",
    mediaIds: [id],
  });

  console.log(JSON.stringify(res, undefined, 2)});
})();
```

Unfortunately, the updated version of this code fails for me with `masto@5.4.0`:

```ts
import { login } from "masto";
import { createReadStream } from "fs";

void (async () => {
  const client = await login({
    url: process.env["MASTODON_SERVER"],
    accessToken: process.env["MASTODON_TOKEN"],
    timeout: 30_000,
  });

  const { id } = await client.v2.mediaAttachments.create({
    file: createReadStream("test.png"),
  });

  const res = await client.v1.statuses.create({
    status: "test",
    visibility: "unlisted",
    mediaIds: [id],
  });

  console.log(JSON.stringify(res, undefined, 2));
})();
```

I receive the following error:

```
<project root>/node_modules/masto/dist/index.cjs:157
            return new MastoHttpUnexpectedError(message, params.statusCode, props);
                   ^
MastoHttpUnexpectedError: Error processing thumbnail for uploaded media
    at createHttpError (<project root>/node_modules/masto/dist/index.cjs:157:20)
    at HttpNativeImpl.<anonymous> (<project root>/node_modules/masto/dist/index.cjs:589:24)
    at Generator.next (<anonymous>)
    at fulfilled (<project root>/node_modules/masto/dist/index.cjs:516:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  isMastoError: true,
  description: 'No further description is provided for this error',
  details: undefined,
  statusCode: 500,
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 500,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Internal Server Error',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: Headers {
      [Symbol(headers list)]: [HeadersList],
      [Symbol(guard)]: 'immutable',
      [Symbol(realm)]: null
    }
  }
}
```

It's not a question of the server's API version -- the server I'm trying to post should have the `v2` endpoint. If I try to use `client.v1.mediaAttachments.create()` instead, I get the following error:

```
<project root>/node_modules/masto/dist/index.cjs:635
                throw new MastoVersionError(`${String(this.constructor.name)}.${String(name)}` +
                      ^
MastoVersionError: MediaAttachmentRepository.create is not available with the current Mastodon version4.0.2 It was removed on version 3.1.3.
    at MediaAttachmentRepository.descriptor.value (<project root>/node_modules/masto/dist/index.cjs:635:23)
    at MediaAttachmentRepository.descriptor.value (<project root>/node_modules/masto/dist/index.cjs:1031:23)
    at <project root>/example.ts:35:51
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  isMastoError: true,
  description: undefined,
  details: undefined,
  [cause]: undefined
}
```

I know the 500 error isn't really helpful... this is more Mastodon's problem than yours. But the fact that this used to work in `masto@4` but fails in `masto@5` seems like a problem for this library to me.

I'm using Node `18.13.0`.

**Comment by neet** [comment]
Hi @lostfictions! The way how to upload a media attachment has been changed in v5 in order to fix #481. Can you try the latest example?
https://github.com/neet/masto.js/blob/main/examples/create-new-status-with-image.ts

You have to pass a `Blob` instance if you’re using Node.js 18.

**Comment by pietervdvn** [comment]
Hi, I had the same issue. This works for me (with node 18): 

```
 const mediaAttachment = await this.instance.v2.mediaAttachments.create({
            file: new Blob([fs.readFileSync(path)]),
            description
        })
        return mediaAttachment.id
        ``

**Comment by lostfictions** [comment]
@neet Thanks for the quick response! That might be a nice thing to include in the [migration guide for 5.0.0](https://github.com/neet/masto.js/releases/tag/v5.0.0), since it seems to be missing...

**Comment by lostfictions** [comment]
Also, does this mean it's no longer possible to pass an instance of `fs.ReadStream` at all?

**Comment by neet** [comment]
@lostfictions Thank you for the advice. I added a link for the migration guide to README #814 and updated it to mention this problem.

> Also, does this mean it's no longer possible to pass an instance of fs.ReadStream at all?

Unfortunately, you're right. This was one of a trade-off for supporting native Fetch API. I wanted to drop Axios because it seemed not to be maintained frequently, had several security issues previously, it increases the bundle size and I determined that it outweighs the Stream API support.

I don't think this is not a critical problem because a Blob instance will be GC'd as soon as media is uploaded, but if you really want to use ReadStream, you can downgrade to Node.js 16 to evade the restriction (but I don't recommend)

**Comment by lostfictions** [comment]
Makes sense! Generally I prefer working with the Streams API when handling files since it's more efficient (and with large files helps avoid OOM errors). But generally Mastodon attachments can't be that big anyway, so it's not a problem in this case.

**Comment by neet** [comment]
@pietervdvn Hi, thank you for the report. I'm closing this issue because original it doesn't seem to be the same problem as the original author faced. Could you open another issue?

Also, since media upload is one of the most intricate features and consists of many layers that depend on your environment, I'm not able to infer what is going on with your code base just by seeing a fragment of source code. I'd be happy if you also include a link to a minimal reproduction repository so that I can check on my machine.

**Comment by pietervdvn** [comment]
@neet Everything works now that I followed your example, so no need to open an issue.

**Comment by neet** [comment]
@pietervdvn OK! I'm glad to hear that 🙏

**Comment by pietervdvn** [comment]
(In case your curious: codebase is here: https://github.com/pietervdvn/MastodonBot; first fully automatic post should be [here](https://botsin.space/@mapcomplete) within the day).
