### ISSUE TITLE
Cant create masto login on Ubuntu - ConnectTimeoutError: Connect Timeout Error

### ISSUE THREAD

**Issue by Melonking906** [neet/masto.js#830]
Iv been pulling my hair out over this one for hours now and I just cant figure it out:

```
const mastoLogin = require("masto");
const masto = await mastoLogin.login({
    url: "XXX",
    accessToken: "XXX",
});
```

Causes this error:
```
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6625:28)
      at node:internal/deps/undici/undici:6583:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6614:13)
      at process.processImmediate (node:internal/timers:471:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

Node.js v18.12.1
```

However it only causes it on my Ubuntu 20.04 VPS, it does not happen when I run the same code locally on macOS - locally it works perfectly fine!
Iv tried multiple node versions including 18.8, 18.12, 19 - all have the same result.
Iv tried installing node via apt and via nvm, same results on both.

I don't know enough about the fetch system to understand what could cause this.

EDIT: Downgrading to v16.19.0 has resolved the issue - at least as a temporary solution.

**Comment by neet** [comment]
@Melonking906 Can you try the following code in your VPS + Node.js 18 environment? It just fetches your instance information and prints the result 

```js
const res = fetch("{Your instance URL}/api/v1/instance");
const data = await res.json()
console.log(data);
```

If it fails, unfortunately it is highly possible to be a problem in either your VPS setup or instance configuration rather than a Masto.js issue.

**Comment by Melonking906** [comment]
It works locally, but fails with the same error on the VPS - so I'll assume its a VPS issue somehow - at least I have an easy way to test it now, thank you!

**Comment by neet** [comment]
Closing since it's apparently unrelated to it. Feel free to re-open if you still have a problem with Masto.js
