### ISSUE TITLE
No module exports in @mastojs/ponyfills

### ISSUE THREAD

**Issue by peterjosling** [neet/masto.js#849]
`masto` supports ES modules as well as CommonJS, but the `@masto/ponyfills` dependency only has CommonJS exports.

I can't find the repo backing this module either. https://www.npmjs.com/package/@mastojs/ponyfills links to https://github.com/neetlab/isomorhpic-web-apis which gives me a 404.

**Comment by neet** [comment]
> https://github.com/neetlab/isomorhpic-web-apis which gives me a 404.

I've forgotten to make it public. Now you can see the source code but here is the right place to post this issue anyways.

It's a module that exports `fetch` `Body` `FormData` and other fetch-related APIs from either the global object or `node-fetch`. It's intended to be a temporary module until Node.js fully supports fetch API in its LTS.

By the way, I totally understand that we should both export ESM and CJS, but which runtime are you using only supporting ESM and not CJS? Node.js switches between CJS/ESM by the `module` field from a package.json. Browsers need to transpile in the first place. I'm curious about your situation and it helps me to triage things a bit.

**Comment by peterjosling** [comment]
I'm playing around with native ESM in the browser without bundling (possible with either `importmap` or rewriting bare imports ahead of time). This quickly falls apart anyway as not all of masto.js's dependencies export modules.

**Comment by neet** [comment]
Closing in favour of #885 -- @mastojs/ponyfills is no longer included
