### ISSUE TITLE
Docs need to be regenerated

### ISSUE THREAD

**Issue by duffn** [neet/masto.js#859]
First, thank you for the great project. 

The docs need to be regenerated. Currently at https://neet.github.io/masto.js/index.html, the initial example shows `masto.statuses.create` and not the correct `masto.v1.statuses.create`. Running the docs locally has `masto.v1.statuses.create`, so I believe that docs only need to be regenerated for https://neet.github.io/masto.js

**Comment by neet** [comment]
Thank you for reporting the issue. I've set up the CD pipeline so docs are now automatically generated via GitHub Actions. I believe this is resolved now.
