### ISSUE TITLE
Type Client is not exported

### ISSUE THREAD

**Issue by ScriptSathi** [neet/masto.js#904]
Hello,

I've noticed that the type `Client` is not exported when I try to use in my project.

![image](https://user-images.githubusercontent.com/73892097/236614754-eb1c9760-5135-420f-9944-b81053af0e88.png)

Did you recommend do it in another way ?

**Comment by neet** [comment]
See #776. I’m planning to improve this in the future release.

**Comment by ScriptSathi** [comment]
@neet Thanks you for your quick answer ! :100:
