### ISSUE TITLE
Very big package

### ISSUE THREAD

**Issue by qertis** [neet/masto.js#952]
Please remove from [npm](https://www.npmjs.com/package/@object-required/masto?activeTab=code) docs files.

<img width="1226" alt="image" src="https://github.com/neet/masto.js/assets/3893228/6e7b802c-ed26-49cd-bc0c-9c2c9fd3829e">

**Comment by qertis** [comment]
Use a .npmignore

**Comment by neet** [comment]
[@object-required/masto](https://www.npmjs.com/package/@object-required/masto) is a fork maintained by someone else. Our upstream build is released under a name [masto](https://www.npmjs.com/package/masto) as it is documented in the README.md

We're explicitly declaring files to distribute in the white list based [files](https://github.com/neet/masto.js/blob/4e997e0b515a3eeb8bfa4c4e047a9a83cb9c4d39/package.json#L77) section of `package.json`, thus I believe there is no need to configure npmignore in addition. 

Here is a screenshot that you can get via `masto`
![image](https://github.com/neet/masto.js/assets/19276905/58afee11-dfe3-4af7-baf6-b76472a7b7fc)

I'm closing this issue, but feel free to reopen if you still have a problem!
